Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-lambdaExecRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - ${arn:aws:logs:ap-southeast-2:${opt:accountId, ''}:log-group:/aws/lambda/*:*:*}
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - ${arn:aws:s3:::*${opt:stage, 'sandpit'}-spacenow-images/*}
