service: api-search
app: api-search
org: arthemus

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  searchListingsByLatLng:
    handler: src/functions/searchListingsByLatLng.main
    events:
      - http:
          path: search/{value}/listings/{latlng}
          method: get
          cors: true
  searchQuery:
    handler: src/functions/searchQuery.main
    events:
      - http:
          path: search/{value}/query
          method: get
          cors: true
